# Username.
[username]
format = "[$user]($style) @ "

# Git & related.
[git_status]
style = "bold blue"

[git_branch]
symbol = "ï¬« "

[git_commit]
tag_symbol = " ï§¸ "

[hg_branch]
symbol = "ï¬« "

# Return status.
[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"

# Timing.
[cmd_duration]
format = "... â³ [$duration]($style)"

# Battery.
[[battery.display]]
threshold = 20

# Nerd Font symbols.
[aws]
symbol = "ï²³ "
style = "bold black"

[cmake]
symbol = "â–³ "
style = "bold black"

[conda]
symbol = "ï„Œ "
style = "bold black"

[crystal]
symbol = "ï”› "
style = "bold black"

[dart]
symbol = "ï„¤ "
style = "bold black"

[deno]
symbol = "îˆœ "
style = "bold black"

[docker_context]
symbol = "ïŒˆ "
style = "bold black"

[dotnet]
symbol = ".NET "
style = "bold black"

[elixir]
symbol = "î‰µ "
style = "bold black"

[elm]
symbol = "î˜¬ "
style = "bold black"

[erlang]
symbol = "î± "
style = "bold black"

[gcloud]
symbol = "ï²³ "
style = "bold black"

[golang]
symbol = "î˜§ "
style = "bold black"

[helm]
symbol = "âˆ "
style = "bold black"

[java]
symbol = "î‰– "
style = "bold black"

[julia]
symbol = "î˜¤ "
style = "bold black"

[kotlin]
symbol = "ï¤° "
style = "bold black"

[kubernetes]
symbol = "â˜¸ "
style = "bold black"

[lua]
symbol = "î˜  "
style = "bold black"

[nim]
symbol = "î‰® "
style = "bold black"

[nix_shell]
symbol = "ï‹œ "
style = "bold black"

[nodejs]
symbol = "ï¢˜ "
style = "bold black"

[ocaml]
symbol = "îŠ¦ "
style = "bold black"

[openstack]
symbol = "ï²³ "
style = "bold black"

[package]
symbol = "ï’‡ "
style = "bold black"

[perl]
symbol = "î© "
style = "bold black"

[php]
symbol = "î˜ˆ "
style = "bold black"

[purescript]
symbol = "<=> "
style = "bold black"

[python]
symbol = "î˜† "
style = "bold black"

[red]
symbol = "ï¨µ "
style = "bold black"

[ruby]
symbol = "î‘ "
style = "bold black"

[rust]
symbol = "ï£ "
style = "bold black"

[scala]
symbol = "îœ· "
style = "bold black"

[singularity]
symbol = "ğŸ†‚ "
style = "bold black"

[swift]
symbol = "î• "
style = "bold black"

[terraform]
symbol = "ï¨ˆ "
style = "bold black"

[vagrant]
symbol = "â± "
style = "bold black"

[vlang]
symbol = "V "
style = "bold black"

[zig]
symbol = "â†¯ "
style = "bold black"

